general {
    ignore_dbus_inhibit = false
    lock_cmd = sh -c "pidof quickshell && qs ipc call quickshell-bar lockscreen"
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = sh -c "sleep 0.3; qs ipc call quickshell-bar wakelock"
}

# Dim screen before lock
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# Lock screen
listener {
    timeout = 180
    on-timeout = loginctl lock-session
    on-resume = sh -c "qs ipc call quickshell-bar wakelock"
}

# Turn off display (disabled - no hyprctl)
# listener {
#     timeout = 300
#     on-timeout = hyprctl dispatch dpms off
#     on-resume = hyprctl dispatch dpms on
# }

# Suspend
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
