{
  config,
  inputs,
  lib,
  pkgs,
  ...
}:
{
  fonts.packages = with pkgs; [
    noto-fonts-cjk-sans
    nerd-fonts.hurmit
    nerd-fonts.hack
    nerd-fonts.fira-code
    nerd-fonts.monoid
    cozette
    sarasa-gothic
    nerd-fonts.jetbrains-mono
    inputs.apple-fonts.packages.${pkgs.stdenv.hostPlatform.system}.sf-pro-nerd
  ];
}
